suissetec_sso_auth:
    sso_server:
        url: '%env(SUISSETEC_SSO_URL)%'
        app_id: '%env(SUISSETEC_SSO_APP_ID)%'
        api_username: '%env(default::SUISSETEC_SSO_API_USERNAME)%'
        api_password: '%env(default::SUISSETEC_SSO_API_PASSWORD)%'

        # Alternative auth instead of username and password:
        # api_bearer_token: '%env(default::SUISSETEC_SSO_API_BEARER_TOKEN)%'

        # Whether to send a logout request to IdP when a user logs out from this application. default: true
        # logout_on_idp: false

    authenticator:
        login_path: '/sso/login'
        check_path: '/sso/callback'

        # Back channel logout path, called by IdP as f.e. /sso/logout?userId=x&loginId=y
        backchannel_logout_path: '/sso/logout'
        # Define a static access token for the back channel logout endpoint.
        # If not defined, the endpoint is public
        # If defined, the token must be added to query params like: /sso/logout?token=...
        # backchannel_access_token: change-me-access-token

        default_target_path: '/'
        failure_path: '/'

        # Check for existing sso user session on public routes (f.e. /^\/(de|fr|it)$/)
        # silent_login_routes:
        #     - /^\/[a-z]{2}\/landingpage$/

    roles:
        # Define default roles appended for any logged-in user, can be empty
        default:
            - ROLE_USER

        # Map interCMS userFunctions to symfony security roles
        # function_mapping:
        #     - appYourAppName: ROLE_USER
        #     - appYourAppNameAdmin: ROLE_ADMIN
