suissetec_sso_auth:
    sso_server:
        url: '%env(SUISSETEC_SSO_URL)%'
        app_id: '%env(SUISSETEC_SSO_APP_ID)%'
        api_username: '%env(default::SUISSETEC_SSO_API_USERNAME)%'
        api_password: '%env(default::SUISSETEC_SSO_API_PASSWORD)%'

        # Alternative auth instead of username and password:
        # api_bearer_token: '%env(default::SUISSETEC_SSO_API_BEARER_TOKEN)%'

        # TTL of session refresh requests to the IdP for reducing the load on the IdP, defaults to 60 seconds
        # session_refresh_ttl: 60

    authenticator:
        login_path: '/sso/login'
        check_path: '/sso/callback'
        default_target_path: '/'
        failure_path: '/'

        # Check for existing sso user session on public routes (f.e. /^\/(de|fr|it)$/)
        # silent_login_routes:
        #     - /^\/[a-z]{2}\/landingpage$/

    roles:
        # Define default roles appended for any logged-in user, can be empty
        default:
            - ROLE_USER

        # Map interCMS userFunctions to symfony security roles
        # function_mapping:
        #     - appYourAppName: ROLE_USER
        #     - appYourAppNameAdmin: ROLE_ADMIN